### ISSUE TITLE
[FEATURE] CPU limit

### ISSUE THREAD

**Issue by maxomatic458** [dylni/process_control#25] opened 2024-04-14 09:09 UTC
It would be cool to also limit a proccesses CPU usage similar to https://github.com/aoldershaw/proclimit

**Comment by dylni** [comment] 2024-04-28 03:28
Duplicate of #26

Closing to avoid multiple issues

**Comment by dylni** [comment] 2024-04-28 03:30
Duplicate of #26

**Comment by dylni** [comment] 2024-04-28 03:30
Closing to avoid multiple issues

**Closed as completed by dylni** 2024-04-28 03:30 UTC
